"""AI processing: streaming STT + answer generation (GPT) + TTS.

Camera audio is recognized streamingly (SpeechKit STT v3, StreamingRecognizer):
- ``begin_segment()`` — start of an utterance (first chunk after a pause): a
  gRPC recognition stream is opened;
- ``process_audio()`` — every PCM chunk goes to the stream immediately;
- ``end_segment()`` — finalization (pause > AUDIO_SEGMENT_GAP or camera
  disconnect): the stream is closed, the utterance text is taken and logged.

After the text is recognized, ``ask()`` runs the answer pipeline in a separate
thread: YandexGPT with the system prompt from the config (yandex.system_prompt)
+ SpeechKit TTS v3 synthesis. The synthesized PCM is returned for playback and
saved for debug next to the recordings (recording.save_tts_audio / save_prompts).

Pictures/faces/emotions are still stubs.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Callable, Dict, List, Optional, Tuple

from . import config as app_config

logger = logging.getLogger("uvicorn")


class Processor:
    """AI pipeline: streaming STT + GPT answer + TTS synthesis."""

    def __init__(self, stt_enabled: bool = True,
                 stt_language: str = "ru-RU",
                 rec: Optional[Any] = None,
                 on_partial: Optional[Callable[[str], None]] = None) -> None:
        from . import yandex as yandex_mod
        self.stt_language = stt_language
        self.stt_enabled = bool(stt_enabled) and yandex_mod.credentials_ok()
        # Called (from the asyncio loop) with the first recognized word of a
        # new utterance — the state machine cancels the emotion decay on it.
        self.on_partial = on_partial
        # True after the first non-empty STT partial of the current segment
        # was reported via on_partial (one report per segment).
        self._first_word_seen = False
        self._stt: Optional[Any] = None
        self._seg_started_at = 0.0
        self.segments = 0       # finished speech segments
        self.recognized = 0     # of those with recognized text
        self.gpt_answers = 0    # answers generated by YandexGPT
        self.tts_synth = 0      # synthesized speech segments (non-empty PCM)
        self.rec = rec          # optional Recorder for debug saving
        y = app_config.CONFIG.get("yandex", {})
        self.gpt_temperature = float(y.get("gpt_temperature", 0.5))
        self.gpt_max_tokens = int(y.get("gpt_max_tokens", 1000))
        self.gpt_enabled = yandex_mod.credentials_ok()
        if not self.stt_enabled:
            logger.warning("[ai] STT disabled: set YANDEX_API_KEY and "
                           "YANDEX_FOLDER_ID (env or config/settings.json)")
        if not self.gpt_enabled:
            logger.warning("[ai] GPT/TTS disabled: no Yandex credentials")

    # ------------------------------------------------------------------
    # Streaming STT (audio segments from the camera).
    # ------------------------------------------------------------------
    async def begin_segment(self) -> None:
        """Utterance start: opens a Yandex STT recognition stream."""
        if not self.stt_enabled or self._stt is not None:
            return
        self._first_word_seen = False
        from . import yandex as yandex_mod
        try:
            stt = yandex_mod.StreamingRecognizer(
                language_code=self.stt_language)
            stt.start()
            self._stt = stt
            self._seg_started_at = time.monotonic()
            logger.info("[ai] STT: segment %d started (stream open)",
                        self.segments + 1)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] STT stream failed to start: %s", exc)
            self._stt = None

    async def process_audio(self, pcm: bytes) -> None:
        """Camera PCM chunk: goes straight into the open recognition stream."""
        if self._stt is not None:
            try:
                self._stt.feed(pcm)
            except Exception as exc:  # noqa: BLE001
                logger.warning("[ai] STT feed error: %s", exc)
            # The first recognized word (STT partial) notifies the caller
            # immediately — the state machine cancels the emotion decay right
            # away, without waiting for the whole segment to finish.
            if not self._first_word_seen:
                try:
                    part = self._stt.drain_partial()
                except Exception:  # noqa: BLE001
                    part = ""
                if part and part.strip():
                    self._first_word_seen = True
                    logger.info("[ai] first word heard: %r", part)
                    if self.on_partial is not None:
                        try:
                            self.on_partial(part)
                        except Exception as exc:  # noqa: BLE001
                            logger.warning("[ai] on_partial callback error: "
                                           "%s", exc)

    def reset_segment(self) -> None:
        """Drops the current STT stream WITHOUT waiting for its result.

        Used by the watchdog when a segment hangs (a stuck gRPC stream would
        otherwise keep the robot silent forever): the stream is aborted and
        the reference is dropped, so the next audio chunk opens a fresh
        recognition stream. Never blocks the asyncio loop.
        """
        if self._stt is not None:
            try:
                self._stt.abort()
            except Exception as exc:  # noqa: BLE001
                logger.warning("[ai] STT abort error: %s", exc)
            self._stt = None
        self._first_word_seen = False
        logger.warning("[ai] STT segment reset (stream dropped)")

    async def end_segment(self) -> str:
        """Utterance finalization: closes the stream and returns the text.

        Does not block the asyncio loop: finish() runs in a separate thread.
        Returns "" if there was no stream or no text was recognized.
        """
        stt = self._stt
        self._stt = None
        if stt is None:
            return ""
        self.segments += 1
        seconds = time.monotonic() - self._seg_started_at
        try:
            text = await asyncio.to_thread(stt.finish)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] STT finish error: %s", exc)
            return ""
        if text:
            self.recognized += 1
            logger.info("[ai] STT segment %d (%.1f s): %r",
                        self.segments, seconds, text)
        else:
            logger.info("[ai] STT segment %d (%.1f s): empty text",
                        self.segments, seconds)
        return text or ""

    # ------------------------------------------------------------------
    # Answer pipeline: YandexGPT + TTS for a recognized utterance.
    # ------------------------------------------------------------------
    async def ask(self, user_text: str) -> Optional[Tuple[bytes, str]]:
        """Generates the robot answer: GPT + TTS for the utterance text.

        Runs blocking calls (ask_gpt, synthesize) in a separate thread so the
        asyncio loop is not frozen. The system prompt and the TTS voice
        parameters come from the config (yandex section). The GPT exchange and
        the synthesized audio are saved for debug (if enabled in recording).

        Returns (pcm, emotion_name) — synthesized speech and the optional
        emotion command extracted from the answer — or None when disabled,
        empty input or on error (the server never crashes because of Yandex).
        """
        if not self.gpt_enabled or not user_text or not user_text.strip():
            return None
        from . import yandex as yandex_mod
        try:
            prompt = yandex_mod.default_system_prompt()
            answer = await asyncio.to_thread(
                yandex_mod.ask_gpt, user_text, prompt,
                temperature=self.gpt_temperature,
                max_tokens=self.gpt_max_tokens)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] GPT error: %s", exc)
            return None
        if not answer or not answer.strip():
            return None
        speech, emotion = yandex_mod.split_emotion(answer)
        if self.rec is not None:
            self.rec.save_prompt_log(prompt, user_text, answer)
        try:
            pcm = await asyncio.to_thread(yandex_mod.synthesize, speech)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] TTS error: %s", exc)
            return None
        self.gpt_answers += 1
        if pcm:
            self.tts_synth += 1
            if self.rec is not None:
                self.rec.save_tts_audio(pcm)
        return (pcm, emotion)

    async def say_emotion(self, emotion: str) -> Optional[bytes]:
        """Emotion-decay phrase: GPT + TTS for the post-dialogue decay.

        Uses the yandex.emotion_decay_prompt system prompt (from settings) so
        the robot says a short phrase matching the decay emotion, then shows
        the emotion. Returns the synthesized PCM (or None on error/empty).
        """
        if not self.gpt_enabled or not emotion:
            return None
        from . import yandex as yandex_mod
        prompt = yandex_mod.default_emotion_decay_prompt()
        try:
            answer = await asyncio.to_thread(
                yandex_mod.ask_gpt, emotion, prompt,
                temperature=self.gpt_temperature,
                max_tokens=self.gpt_max_tokens)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] emotion-decay GPT error: %s", exc)
            return None
        if not answer or not answer.strip():
            return None
        speech, _ = yandex_mod.split_emotion(answer)
        if self.rec is not None:
            self.rec.save_prompt_log(
                prompt, f"[decay:{emotion}]", answer)
        try:
            pcm = await asyncio.to_thread(yandex_mod.synthesize, speech)
        except Exception as exc:  # noqa: BLE001
            logger.warning("[ai] emotion-decay TTS error: %s", exc)
            return None
        if pcm and self.rec is not None:
            self.rec.save_tts_audio(pcm)
        return pcm or None

    def health(self) -> Dict[str, Any]:
        """STT/GPT/TTS statistics for /health."""
        return {
            "stt_enabled": self.stt_enabled,
            "stt_segments": self.segments,
            "stt_recognized": self.recognized,
            "gpt_enabled": self.gpt_enabled,
            "gpt_answers": self.gpt_answers,
            "tts_synth": self.tts_synth,
        }

    # ------------------------------------------------------------------
    # Picture pipeline (discrete frames, no video stream).
    # ------------------------------------------------------------------
    async def detect_objects(self, jpeg: bytes) -> List[Dict[str, Any]]:
        """Object recognition on a JPEG picture. Stub: empty detections."""
        logger.info("[ai] detect_objects: JPEG %d bytes (stub — 0 objects)",
                    len(jpeg))
        return []

    async def on_face(self, face_id: str,
                      confidence: Any = None) -> None:
        """Recognized-face event from the camera. Stub: log only."""
        logger.info("[ai] face: id=%r confidence=%s (stub)",
                    face_id, confidence)

    async def on_camera_emotion(self, emotion: str) -> None:
        """Face emotion recognized by the camera. Stub: log only."""
        logger.info("[ai] face emotion: %r (stub)", emotion)

    async def on_robot_text(self, text: str) -> None:
        """Text from the robot. Stub: log only."""
        logger.info("[ai] robot text: %r (stub)", text)